services:
  - type: web
    name: frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
  - type: web
    name: backend
    plan: free
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node index.js
    healthCheckPath: /
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://dbUser:Reddy7989@dineshreddy.go8zyiz.mongodb.net/mental_health_db?retryWrites=true&w=majority
      - key: CORS_ORIGIN
        value: https://user-based-tuning-project.onrender.com