services:
  # Backend Service (Web Service)
  - type: web
    name: backend
    env: node
    rootDir: .
    buildCommand: cd frontend && npm install && npm run build && cd ../backend && npm install
    startCommand: node backend/index.js
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        value: https://smart-learners-1.onrender.com